"""Functional test generator using Robot Framework."""

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

from officeboy.access.application import AccessApplication
from officeboy.access.objects import AccessObjectType, FormInfo, FormControl
from officeboy.i18n import get_text as _

logger = logging.getLogger(__name__)


@dataclass
class FunctionalTestStats:
    """Statistics for functional test generation."""
    
    spec_count: int = 0
    form_count: int = 0
    test_case_count: int = 0


class FunctionalTestGenerator:
    """Generates Robot Framework tests for MS Access forms."""
    
    # Robot Framework template for test suite
    ROBOT_HEADER = '''*** Settings ***
Documentation     Auto-generated functional tests for {form_name} form
...               Generated by Officeboy
Library           {library}
Library           OperatingSystem
Suite Setup       Open Access Application    {access_file}
Suite Teardown    Close Access Application
Test Setup        Navigate To Form    {form_name}

*** Variables ***
${{FORM_NAME}}    {form_name}
${{ACCESS_FILE}}  {access_file}

'''
    
    # Template for button click test
    BUTTON_TEST_TEMPLATE = '''
*** Test Cases ***
{test_name}
    [Documentation]    Test {button_name} button click handler
    [Tags]    form    button    {form_name}
    
    # Verify form is open
    Form Should Be Open    ${{FORM_NAME}}
    
    # Verify button exists
    Control Should Exist    ${{FORM_NAME}}    {button_name}
    
    # Get initial state (if applicable)
    ${initial_state}=    Get Control State    ${{FORM_NAME}}    {control_name}
    
    # Click button
    Click Button    ${{FORM_NAME}}    {button_name}
    
    # Verify expected behavior based on event handler: {event_handler}
    {verification_steps}
    
    [Teardown]    Run Keyword If Test Failed    Capture Screenshot    {test_name}_failed.png

'''
    
    # Template for form load test
    FORM_LOAD_TEMPLATE = '''
*** Test Cases ***
{form_name} Form Load Test
    [Documentation]    Verify {form_name} form loads correctly
    [Tags]    form    load    smoke
    
    # Open form
    Open Form    ${{FORM_NAME}}
    
    # Verify form is displayed
    Form Should Be Open    ${{FORM_NAME}}
    
    # Verify title
    Form Title Should Be    ${{FORM_NAME}}    {expected_title}
    
    # Verify key controls exist
    {control_verifications}
    
    [Teardown]    Close Form    ${{FORM_NAME}}

'''
    
    # Python library template for Access automation
    PYTHON_LIBRARY_TEMPLATE = '''#!/usr/bin/env python3
"""Auto-generated Robot Framework library for Access automation."""

from FlaUILibrary import FlaUILibrary
from robot.api.deco import keyword
from typing import Optional
import subprocess
import time


class AccessLibrary:
    """Robot Framework library for MS Access automation."""
    
    ROBOT_LIBRARY_SCOPE = 'GLOBAL'
    
    def __init__(self):
        self.flaui = FlaUILibrary()
        self.access_process = None
        self.main_window = None
    
    @keyword
    def open_access_application(self, database_path: str):
        """Open MS Access with specified database."""
        # Launch Access
        self.access_process = subprocess.Popen([
            'msaccess.exe',
            database_path,
            '/runtime'  # Run in runtime mode if available
        ])
        time.sleep(3)  # Wait for Access to load
        
        # Attach to window using FlaUI
        self.main_window = self.flaui.attach_window_by_name("Microsoft Access")
    
    @keyword
    def close_access_application(self):
        """Close MS Access."""
        if self.access_process:
            self.access_process.terminate()
            self.access_process.wait()
    
    @keyword
    def navigate_to_form(self, form_name: str):
        """Navigate to specified form."""
        # Implementation depends on Access UI structure
        pass
    
    @keyword
    def open_form(self, form_name: str):
        """Open a form by name."""
        # Use Access automation or UI navigation
        pass
    
    @keyword
    def close_form(self, form_name: str):
        """Close the specified form."""
        pass
    
    @keyword
    def form_should_be_open(self, form_name: str):
        """Verify form is currently open."""
        pass
    
    @keyword
    def form_title_should_be(self, form_name: str, expected_title: str):
        """Verify form title."""
        pass
    
    @keyword
    def control_should_exist(self, form_name: str, control_name: str):
        """Verify control exists on form."""
        pass
    
    @keyword
    def click_button(self, form_name: str, button_name: str):
        """Click a button on the form."""
        # Use FlaUI to find and click button
        button = self.flaui.get_control_by_name(button_name)
        button.click()
    
    @keyword
    def get_control_state(self, form_name: str, control_name: str):
        """Get current state of a control."""
        pass
    
    @keyword
    def set_control_value(self, form_name: str, control_name: str, value: str):
        """Set value of a control."""
        pass
    
    @keyword
    def capture_screenshot(self, filename: str):
        """Capture screenshot on failure."""
        self.flaui.capture_screenshot(filename)
'''
    
    def __init__(
        self,
        access_file: Path,
        output_dir: Path,
        library: str = "FlaUILibrary",
    ) -> None:
        """Initialize functional test generator.
        
        Args:
            access_file: Path to Access database.
            output_dir: Directory for output files.
            library: Robot Framework library to use.
        """
        self.access_file = Path(access_file)
        self.output_dir = Path(output_dir)
        self.library = library
        self.app = AccessApplication()
        self.stats = FunctionalTestStats()
        
    def _generate_control_verifications(self, form_info: FormInfo) -> str:
        """Generate verification steps for form controls.
        
        Args:
            form_info: Form information.
            
        Returns:
            Robot Framework code for control verification.
        """
        lines = []
        
        if form_info.controls:
            for ctl in form_info.controls[:5]:  # Limit to first 5 controls
                lines.append(
                    f"Control Should Exist    ${{FORM_NAME}}    {ctl.name}"
                )
        
        return "\n    ".join(lines) if lines else "No Operation"
    
    def _generate_button_verification(self, 
                                       ctl: FormControl, 
                                       event_handler: str) -> str:
        """Generate verification steps based on event handler.
        
        Args:
            ctl: Control information.
            event_handler: Event handler code/procedure.
            
        Returns:
            Robot Framework verification steps.
        """
        handler_lower = event_handler.lower()
        
        # Analyze event handler to determine expected behavior
        if "close" in handler_lower or "quit" in handler_lower:
            return '''
    # Expected: Form should close
    Sleep    1s
    Form Should Not Be Open    ${FORM_NAME}
'''
        elif "save" in handler_lower or "update" in handler_lower:
            return '''
    # Expected: Record should be saved
    Sleep    500ms
    Status Message Should Contain    Saved
'''
        elif "open" in handler_lower or "show" in handler_lower:
            return '''
    # Expected: Another form/dialog should open
    Sleep    1s
    ${new_window}=    Get Active Window
    Should Not Be Empty    ${new_window}
'''
        elif "msgbox" in handler_lower or "message" in handler_lower:
            return '''
    # Expected: Message box should appear
    Sleep    500ms
    Dialog Should Be Visible
    Click Button On Dialog    OK
'''
        else:
            return '''
    # Expected: No error should occur
    Sleep    500ms
    No Error Dialog Should Be Visible
'''
    
    def _generate_form_tests(self, form_info: FormInfo) -> str:
        """Generate test suite for a form.
        
        Args:
            form_info: Form information.
            
        Returns:
            Complete Robot Framework test suite.
        """
        test_cases = []
        
        # Form load test
        test_cases.append(self.FORM_LOAD_TEMPLATE.format(
            form_name=form_info.name,
            expected_title=form_info.name,
            control_verifications=self._generate_control_verifications(form_info),
        ))
        self.stats.test_case_count += 1
        
        # Button tests
        if form_info.controls:
            for ctl in form_info.controls:
                # Check for click event
                click_handler = ctl.event_handlers.get("OnClick", "")
                
                if click_handler and ctl.control_type in ("CommandButton", "Button"):
                    test_name = f"{form_info.name} {ctl.name} Button Test"
                    
                    verification = self._generate_button_verification(
                        ctl, click_handler
                    )
                    
                    test_cases.append(self.BUTTON_TEST_TEMPLATE.format(
                        test_name=test_name,
                        button_name=ctl.name,
                        control_name=ctl.name,
                        form_name=form_info.name,
                        event_handler=click_handler,
                        verification_steps=verification,
                    ))
                    self.stats.test_case_count += 1
        
        # Combine into full suite
        header = self.ROBOT_HEADER.format(
            form_name=form_info.name,
            access_file=str(self.access_file),
            library=self.library,
        )
        
        return header + "\n".join(test_cases)
    
    def _generate_resource_file(self) -> str:
        """Generate shared resource file.
        
        Returns:
            Robot Framework resource file content.
        """
        return '''*** Settings ***
Documentation    Shared keywords and variables for Access testing
Library          OperatingSystem
Library          String

*** Keywords ***
No Error Dialog Should Be Visible
    [Documentation]    Verify no error dialog is shown
    ${has_error}=    Is Error Dialog Visible
    Should Not Be True    ${has_error}    An unexpected error dialog appeared

Status Message Should Contain
    [Arguments]    ${expected_text}
    [Documentation]    Verify status bar contains expected text
    ${status}=    Get Status Bar Text
    Should Contain    ${status}    ${expected_text}

Form Should Not Be Open
    [Arguments]    ${form_name}
    [Documentation]    Verify form is closed
    ${is_open}=    Is Form Open    ${form_name}
    Should Not Be True    ${is_open}    Form ${form_name} should be closed
'''
    
    def generate(self) -> FunctionalTestStats:
        """Generate functional tests for all forms.
        
        Returns:
            Statistics for generation.
        """
        try:
            self.app.open_database(self.access_file)
            
            # Get all forms
            forms = self.app.get_objects(AccessObjectType.FORM)
            
            self.output_dir.mkdir(parents=True, exist_ok=True)
            
            # Generate Python library
            lib_path = self.output_dir / "AccessLibrary.py"
            with open(lib_path, "w", encoding="utf-8") as f:
                f.write(self.PYTHON_LIBRARY_TEMPLATE)
            
            # Generate resource file
            resource_path = self.output_dir / "common.resource"
            with open(resource_path, "w", encoding="utf-8") as f:
                f.write(self._generate_resource_file())
            
            # Generate test for each form
            for form_summary in forms:
                form_info = self.app.get_form_info(form_summary.name)
                
                if not form_info:
                    continue
                
                test_content = self._generate_form_tests(form_info)
                
                # Write test file
                test_filename = f"{form_info.name}_tests.robot"
                test_path = self.output_dir / test_filename
                
                with open(test_path, "w", encoding="utf-8") as f:
                    f.write(test_content)
                
                self.stats.spec_count += 1
                self.stats.form_count += 1
                
                logger.info(
                    _("Generated tests for form {form}: {count} test cases").format(
                        form=form_info.name,
                        count=self.stats.test_case_count,
                    )
                )
            
            # Generate __init__.py for Python path
            init_path = self.output_dir / "__init__.py"
            init_path.touch()
            
            return self.stats
            
        finally:
            self.app.close_database()