"""Unit test generator for MS Access VBA modules."""

import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

from officeboy.access.application import AccessApplication
from officeboy.access.objects import AccessObjectType
from officeboy.i18n import get_text as _

logger = logging.getLogger(__name__)


@dataclass
class VbaProcedure:
    """Information about a VBA procedure."""
    
    name: str
    procedure_type: str  # "Function" or "Sub"
    is_public: bool
    parameters: List[str]
    return_type: Optional[str] = None


@dataclass
class UnitTestStats:
    """Statistics for unit test generation."""
    
    module_count: int = 0
    test_count: int = 0


class UnitTestGenerator:
    """Generates unit test add-ins for MS Access."""
    
    # VBA template for test module header
    TEST_MODULE_HEADER = '''Attribute VB_Name = "{test_module_name}"
' {test_module_name} - Auto-generated unit tests for {source_module}
' Generated by Officeboy
' https://github.com/yorgabr/officeboy

Option Compare Database
Option Explicit

' Test result tracking
Private m_testCount As Long
Private m_passCount As Long
Private m_failCount As Long

'''
    
    # Template for test procedure
    TEST_PROCEDURE_TEMPLATE = '''
' Test Method: {test_name}
' Tests: {source_procedure}
Public Sub {test_name}()
    On Error GoTo ErrorHandler
    
    ' Arrange
    Dim result As {return_type}
    {arrange_code}
    
    ' Act
    result = {call_code}
    
    ' Assert
    Assert{assertion_type} result, {expected_value}, "{message}"
    
    Exit Sub
ErrorHandler:
    TestFailed "{test_name}", Err.Description
End Sub

'''
    
    def __init__(
        self,
        access_file: Path,
        output_dir: Path,
        addin_name: str = "OfficeboyTests",
    ) -> None:
        """Initialize unit test generator.
        
        Args:
            access_file: Path to Access database.
            output_dir: Directory for output files.
            addin_name: Name of the generated add-in.
        """
        self.access_file = Path(access_file)
        self.output_dir = Path(output_dir)
        self.addin_name = addin_name
        self.app = AccessApplication()
        self.stats = UnitTestStats()
        
    def _parse_module_code(self, code: str) -> List[VbaProcedure]:
        """Parse VBA code to extract public procedures.
        
        Args:
            code: VBA source code.
            
        Returns:
            List of procedure information.
        """
        procedures = []
        
        # Regex patterns for procedure detection
        # Matches: Public Function Name(params) As Type
        # Matches: Public Sub Name(params)
        func_pattern = re.compile(
            r'^\s*Public\s+(Function|Sub)\s+(\w+)\s*\(([^)]*)\)'
            r'(?:\s+As\s+(\w+))?',
            re.MULTILINE | re.IGNORECASE
        )
        
        for match in func_pattern.finditer(code):
            proc_type = match.group(1).capitalize()
            name = match.group(2)
            params_str = match.group(3).strip()
            return_type = match.group(4)
            
            # Parse parameters
            params = []
            if params_str:
                # Simple parameter parsing
                for param in params_str.split(","):
                    param = param.strip()
                    if param:
                        # Extract parameter name (before type or As)
                        param_parts = param.split()
                        if param_parts:
                            params.append(param_parts[0])
            
            procedures.append(VbaProcedure(
                name=name,
                procedure_type=proc_type,
                is_public=True,
                parameters=params,
                return_type=return_type if proc_type == "Function" else None,
            ))
        
        return procedures
    
    def _generate_test_name(self, proc_name: str) -> str:
        """Generate test method name from procedure name.
        
        Args:
            proc_name: Original procedure name.
            
        Returns:
            Test method name.
        """
        return f"Test{proc_name}"
    
    def _generate_arrange_code(self, proc: VbaProcedure) -> str:
        """Generate Arrange section of test.
        
        Args:
            proc: Procedure information.
            
        Returns:
            VBA code for test setup.
        """
        lines = []
        
        # Generate parameter setup
        for i, param in enumerate(proc.parameters):
            # Generate dummy values based on common naming conventions
            if "id" in param.lower():
                lines.append(f"Dim {param} As Long: {param} = 1")
            elif "name" in param.lower():
                lines.append(f"Dim {param} As String: {param} = \"Test\"")
            elif "date" in param.lower():
                lines.append(f"Dim {param} As Date: {param} = Now()")
            else:
                lines.append(f"Dim {param} As Variant: {param} = Null")
        
        return "\n    ".join(lines) if lines else "' No parameters"
    
    def _generate_call_code(self, proc: VbaProcedure) -> str:
        """Generate Act section - the actual call.
        
        Args:
            proc: Procedure information.
            
        Returns:
            VBA code for calling the procedure.
        """
        params = ", ".join(proc.parameters)
        
        if proc.procedure_type == "Function":
            return f"{proc.name}({params})"
        else:
            return f"' Call Sub: {proc.name} {params}"
    
    def _generate_assertion(self, proc: VbaProcedure) -> Tuple[str, str, str]:
        """Generate assertion for test.
        
        Args:
            proc: Procedure information.
            
        Returns:
            Tuple of (assertion_type, expected_value, message).
        """
        if proc.return_type:
            type_lower = proc.return_type.lower()
            if "boolean" in type_lower:
                return "IsTrue", "True", f"{proc.name} should return True"
            elif "long" in type_lower or "integer" in type_lower:
                return "Equals", "0", f"{proc.name} return value"
            elif "string" in type_lower:
                return "Equals", "\"\"", f"{proc.name} return value"
            else:
                return "IsNotNull", "result", f"{proc.name} should not return Nothing"
        else:
            return "NoError", "True", f"{proc.name} should execute without error"
    
    def _generate_test_procedure(self, proc: VbaProcedure, 
                                  source_module: str) -> str:
        """Generate test procedure for a VBA procedure.
        
        Args:
            proc: Procedure to test.
            source_module: Name of source module.
            
        Returns:
            VBA test code.
        """
        test_name = self._generate_test_name(proc.name)
        arrange_code = self._generate_arrange_code(proc)
        call_code = self._generate_call_code(proc)
        assertion_type, expected_value, message = self._generate_assertion(proc)
        
        return self.TEST_PROCEDURE_TEMPLATE.format(
            test_name=test_name,
            source_procedure=proc.name,
            return_type=proc.return_type or "Variant",
            arrange_code=arrange_code,
            call_code=call_code,
            assertion_type=assertion_type,
            expected_value=expected_value,
            message=message,
        )
    
    def _generate_test_module(self, module_name: str, 
                               procedures: List[VbaProcedure]) -> str:
        """Generate complete test module.
        
        Args:
            module_name: Name of source module.
            procedures: List of procedures to test.
            
        Returns:
            Complete VBA module code.
        """
        test_module_name = f"{module_name}Test"
        
        code_parts = [
            self.TEST_MODULE_HEADER.format(
                test_module_name=test_module_name,
                source_module=module_name,
            )
        ]
        
        # Add test procedures
        for proc in procedures:
            if proc.is_public:
                code_parts.append(
                    self._generate_test_procedure(proc, module_name)
                )
                self.stats.test_count += 1
        
        # Add test runner
        code_parts.append(self._generate_test_runner(test_module_name))
        
        return "\n".join(code_parts)
    
    def _generate_test_runner(self, module_name: str) -> str:
        """Generate test runner code.
        
        Args:
            module_name: Name of test module.
            
        Returns:
            VBA test runner code.
        """
        return f'''
' Run all tests in this module
Public Sub RunAllTests()
    m_testCount = 0
    m_passCount = 0
    m_failCount = 0
    
    Dim proc As Variant
    For Each proc In Array("Test...")
        ' Call test procedures
        ' This is a simplified version - full implementation would
        ' use reflection to call all Test* procedures
    Next proc
    
    MsgBox "Tests: " & m_testCount & vbCrLf & _
           "Passed: " & m_passCount & vbCrLf & _
           "Failed: " & m_failCount, _
           vbInformation, "Test Results"
End Sub

' Assertion helpers
Private Sub AssertEquals(actual As Variant, expected As Variant, msg As String)
    m_testCount = m_testCount + 1
    If actual = expected Then
        m_passCount = m_passCount + 1
    Else
        m_failCount = m_failCount + 1
        Debug.Print "FAIL: " & msg & " - Expected: " & expected & ", Got: " & actual
    End If
End Sub

Private Sub AssertIsTrue(value As Boolean, expected As Boolean, msg As String)
    m_testCount = m_testCount + 1
    If value = expected Then
        m_passCount = m_passCount + 1
    Else
        m_failCount = m_failCount + 1
        Debug.Print "FAIL: " & msg
    End If
End Sub

Private Sub AssertIsNotNull(value As Variant, dummy As String, msg As String)
    m_testCount = m_testCount + 1
    If Not IsNothing(value) Then
        m_passCount = m_passCount + 1
    Else
        m_failCount = m_failCount + 1
        Debug.Print "FAIL: " & msg
    End If
End Sub

Private Sub TestFailed(testName As String, errMsg As String)
    m_failCount = m_failCount + 1
    Debug.Print "ERROR in " & testName & ": " & errMsg
End Sub
'''
    
    def generate(self) -> UnitTestStats:
        """Generate unit tests for all modules.
        
        Returns:
            Statistics for generation.
        """
        try:
            self.app.open_database(self.access_file)
            
            # Get all modules
            modules = self.app.get_objects(AccessObjectType.MODULE)
            
            self.output_dir.mkdir(parents=True, exist_ok=True)
            
            for module_info in modules:
                # Export module code
                code = self.app.export_object(module_info)
                
                if not code:
                    continue
                
                # Parse procedures
                procedures = self._parse_module_code(code)
                
                if not procedures:
                    continue
                
                # Generate test module
                test_code = self._generate_test_module(
                    module_info.name,
                    procedures,
                )
                
                # Write test file
                test_filename = f"{module_info.name}Test.bas"
                test_path = self.output_dir / test_filename
                
                with open(test_path, "w", encoding="utf-8") as f:
                    f.write(test_code)
                
                self.stats.module_count += 1
                logger.info(
                    _("Generated tests for {module}: {count} tests").format(
                        module=module_info.name,
                        count=len([p for p in procedures if p.is_public]),
                    )
                )
            
            # Generate add-in manifest
            self._generate_addin_manifest()
            
            return self.stats
            
        finally:
            self.app.close_database()
    
    def _generate_addin_manifest(self) -> None:
        """Generate add-in manifest file."""
        manifest = f'''<?xml version="1.0" encoding="UTF-8"?>
<AddIn Name="{self.addin_name}" 
       FullName="Officeboy Unit Tests" 
       Description="Auto-generated unit tests"
       Version="1.0">
    <Modules>
'''
        
        # List all test modules
        for test_file in self.output_dir.glob("*Test.bas"):
            manifest += f'        <Module Name="{test_file.stem}" File="{test_file.name}" />\n'
        
        manifest += '''    </Modules>
</AddIn>
'''
        
        manifest_path = self.output_dir / f"{self.addin_name}.xml"
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write(manifest)